title: Talon for Dragon Users
author: Anders Schneiderman
email: your-email@domain.com
description:  Switching to Talon

# Menu data for sitewide navigation
navigation_links:
  - name: 'Writing'
    link: 'pages/writing/writing.html'
  - name: Cursorless
    link: 'pages/writing/cursorless.html'
  - name: Applications
    link: 'pages/apps/applications.html'
  - name: Scripting
    link: 'pages/scripting/scripting-talon.html'
  - name: Up Next
    link: 'pages/up-next.html'
  
  